<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>Moose</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(has)\b</string>
			<key>name</key>
			<string>keyword.attribute</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(with)\b</string>
			<key>name</key>
			<string>keyword.role</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(extends)\b</string>
			<key>name</key>
			<string>keyword.extends</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(before|around|after)\b</string>
			<key>name</key>
			<string>keyword.method.modifiers</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(override|super)\b</string>
			<key>name</key>
			<string>keyword.method.override</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(augment|inner)\b</string>
			<key>name</key>
			<string>keyword.method.augment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(type|subtype|enum|class_type)\b</string>
			<key>name</key>
			<string>keyword.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|where)\b</string>
			<key>name</key>
			<string>keyword.type.modifiers</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(coerce)\b</string>
			<key>name</key>
			<string>keyword.type.coercion</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(via|from)\b</string>
			<key>name</key>
			<string>keyword.type.coercion.modifiers</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(requires)\b</string>
			<key>name</key>
			<string>keyword.role.requires</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(excludes)\b</string>
			<key>name</key>
			<string>keyword.role.excludes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.perl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.perl.moose</string>
	<key>uuid</key>
	<string>09D0B47F-8CF4-498E-ABB0-CFDA07749A16</string>
</dict>
</plist>
